[build]
  command = "yarn build"
  publish = "dist"
  functions = ".netlify/functions"

[dev]
  command = "vite"
  targetPort = 8080   # Vite dev server 포트
  port = 3000         # Netlify dev가 실행될 포트
  framework = "#custom"
